; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	lvgl/lvgl@^9.3.0
	bodmer/TFT_eSPI@^2.5.43
monitor_speed = 115200
build_flags =
  -I include
  ;###############################################################
  ; TFT_eSPI library setting here (no need to edit library files):
  ;###############################################################
  -D USER_SETUP_LOADED=1                        ; Set this settings as valid
  -D ILI9341_DRIVER=1                           ; Select ILI9341_DRIVER driver
  -D TFT_MISO=19                                ; Define SPI pins
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=15
  -D TFT_DC=2                                   ; Data/Comand pin
  -D TFT_RST=4                                  ; Reset pin
  -D TOUCH_CS=21
  -D SPI_FREQUENCY=40000000                     ; Set SPI frequency

; build_src_filter =
;     +<*>
;     ; Force compile LVGL demos and examples, remove when working on your own project
;     +<../.pio/libdeps/${PIOENV}/lvgl/demos>
;     +<../.pio/libdeps/${PIOENV}/lvgl/examples>